Objects
42njaber/notrealengine pull request #4
Opened 2021-11-19 08:32 UTC by lnicosia

First basic implementation of 3D objets: Mesh and MeshObject classes, with assimp for model loading and stb_image for image loading.

2021-12-03 01:33 UTC, 42njaber requested changes

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		GLMesh();
Je ne suis pas sur que ce soit une bonne idée d'avoir un default constructor, ça veux dire que nos GLMesh peuvent commencer dans un état invalide, ça serait peut-être mieux de garder uniquement le constructeur qui créé un GLMesh utilisable.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		GLMesh(GLMesh const & mesh);
Le copy constructor devrait être un move constructor `GLMesh(GLMesh && mesh)`, qui met les références des VAO, VBO et EBO à 0 dans l'autre objet pour les noter comme invalide. Si jamais on as 2 GLMesh qui ont les mêmes VAO/etc on finira toujours avec des objets GLMesh invalides qui ont eu leur références OpenGL delete mais qui le savent pas ce qui est déjà un problème en soit, mais ils et vont aussi essayer de les delete dans leur destructor.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		GLMesh& operator=(GLMesh const& mesh);
Pareil que pour le copy-constructor, devrait être changé en `GLMesh& operator=(GLMesh && mesh)` et appeler le move constructor. Peut-être même l'enlever totalement et autoriser uniquement les move par construction (genre `GLMesh newMesh(oldMesh)`), pour qu'on rende pas accidentellement notre objet invalid parce-que on a oublié que il fonctionne en move.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		MeshData const	getData() const;
Pour l'opti, mieux vaux renvoyer `const MeshData &`, sinon l'objet est copié à chaque appel.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		unsigned int const	getPolygonMode() const;
idem pour `const unsigned int &`

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			std::string	name;
Pourquoi name est en public et modifiable?

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			GLObject(std::string path);
Pourquoi pas avoir un ObjectData comme pour MeshData et construire ObjectData via std::string, et passer ObjectData à GLObject?

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		MeshData		data;
On a besoin de stocker une copie du MeshData dans le GLMesh?

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			std::vector<std::shared_ptr<GLMesh>>		meshes;
`std::vector<std::shared_ptr<const GLMesh>>` serait peut-être mieux, je pense pas qu'on aie à modifier les GLMesh aprés la création, sinon, il faudrait au moins que le vecteur renvoie de cette façon, sinon les Meshs peuvent être modifiés avec le getter.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +				getMeshes() const;
Idem, const ref

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			mft::mat4	getMatrix() const;
Idem, const ref

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			std::vector<Texture>	loadedTextures;
Ca devrait probablement être un `std::shared_ptr<Texture>` vu que Texture est une resource. Et aussi, on peut pas mettre ça dans GLMesh au lieu des GLObject? Et probablement avec un texture manager aussi, sinon on vas devoir charger chaque texture chaque fois qu'on créée une nouvelle instance d'objet

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			std::string	directory;
On devrait peut-être pas avoir ça là, en théorie ça devrait être possible de pouvoir créer un GLObjet entièrement au runtime, auquel cas on aurait pas de directory. Peut-être mettre ça dans un système de prefab comme Unity, vu que actuellement, quand on copie un objet pour l’instancier, on copie aussi le state de l'objet, ce qui est pas idéal.

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +			mft::mat4	matrix;
Ou pourrait peut-être mettre la matrice dans Transform, avec un système de dirty flag qui recalcule la matrice que si le transform a été modifié quand on appel `Transform.getMatrix()`?

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/MeshData.class.hpp
> +		unsigned int	id;
Pour la gestion de resources, Texture devrait avoir ses propre constructors et son destructor, et l'id ne devrait pas être public et modifiable

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +				processMesh(aiMesh* mesh, const aiScene* scene);
idem

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +				loadMaterialTextures(aiMaterial* mat, aiTextureType type, std::string typeName);
idem

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +				loadTexture(std::string file, std::string directory);
Devrai probablement être `static`

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/MeshData.class.hpp
> +		mft::mat4	matrix;
MeshData devrait pas avoir de Transform, c'est censé être une donné invariable, les matrices sont censées être gérée par les objets, sinon, quand les objets partagent des mesh (ce qu'on devrait faire si on veut que notre engine ait un minimum de perfs), ils vont entrer en conflit les uns avec les autres.

2021-12-03 01:33 UTC, 42njaber commented on src/Object/GLMesh.class.cpp
> +		this->EBO = GLMesh.EBO;
SI on garde cet operateur, il faut delete les anciens VAO, VBO et EBO avant de copier les nouveaux, sinon c'est un leak

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		void	scale(mft::vec3 scale);
GLMesh devrait pas avoir de transformation (cf commentaire sur MeshData)

2021-12-03 01:33 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		void	draw(GLShaderProgram *shader) const;
draw devrait prendre en argument une matrice de transformation envoyée par GLObject.

2021-12-03 01:33 UTC, 42njaber commented on src/Object/GLMesh.class.cpp
> +		GLCallThrow(glUniformMatrix4fv, glGetUniformLocation(shader->programID, "mesh_model"), 1, GL_FALSE, &data.getMatrix()[0][0]);
On peut faire `static_cast<float *>(data.getMatrix())` pour plus de lisibilité, vu que j'ai ajouté la conversion explicite

2021-12-03 13:24 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		GLMesh();
Ok, dans ce cas la déclarer le constructeur par défaut en `= delete`

2021-12-03 13:25 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		MeshData const	getData() const;
Yes

2021-12-03 13:25 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		unsigned int const	getPolygonMode() const;
Yes

2021-12-03 13:26 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			std::string	name;
Pour moi le nom libre d'access etait plutot logique. Ca reste plus propre de le mettre private et de rajouter getter et setter.

2021-12-03 13:27 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			std::vector<std::shared_ptr<GLMesh>>		meshes;
Pour le coup leur transform (et matrice) vont être modifiées pendant les animations si on reste sur cette structure de données, à voir.

2021-12-03 13:28 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +				getMeshes() const;
Comme dit au dessus, on peut avoir besoin de modifier les meshes et le seul accès possible se fait par ce get(), donc a voir.

2021-12-03 13:30 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			std::vector<Texture>	loadedTextures;
Le but du loadedTexture c'est uniquement de faire le rôle de texture manager, les textures sont réalité stockées dans le MeshData (elles doivent être indépendants de l'OpenGL autant que possible et sont liées à un mesh) 
Effectivement les stocker en shared_ptr peut beaucoup aider a conserver leur unicité

2021-12-03 13:32 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			mft::mat4	matrix;
Pourquoi pas, pareil pour les GLMesh

2021-12-03 13:35 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			mft::mat4	getMatrix() const;
Là oui

2021-12-03 13:44 UTC, lnicosia commented on inc/Object/MeshData.class.hpp
> +		mft::mat4	matrix;
Effectivement ça devrait être dans le GLMesh, ça va avec la restructuration des données

2021-12-03 13:45 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		GLMesh(GLMesh const & mesh);
On va restructurer les données proprements

2021-12-03 13:45 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		GLMesh& operator=(GLMesh const& mesh);
-> Restructuration des données

2021-12-03 13:45 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			GLObject(std::string path);
-> Restructuration des données

2021-12-03 13:45 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		MeshData		data;
Il faudrait une ref -> Restructuration des données

2021-12-03 13:47 UTC, lnicosia commented on inc/Object/MeshData.class.hpp
> +		unsigned int	id;
-> Restructuration des données

2021-12-03 13:47 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +				processMesh(aiMesh* mesh, const aiScene* scene);
Idem de? Je dois pas avoir les commentaires dans le bon ordre

2021-12-03 13:47 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +				loadTexture(std::string file, std::string directory);
-> Restructuration des données

2021-12-03 13:47 UTC, lnicosia commented on src/Object/GLMesh.class.cpp
> +		this->EBO = GLMesh.EBO;
-> Restructuration des données

2021-12-03 13:49 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		void	draw(GLShaderProgram *shader) const;
On peut bind la matrice de l'objet au shader directement dans l'objet, le mesh en a pas besoin

2021-12-03 13:49 UTC, lnicosia commented on src/Object/GLMesh.class.cpp
> +		GLCallThrow(glUniformMatrix4fv, glGetUniformLocation(shader->programID, "mesh_model"), 1, GL_FALSE, &data.getMatrix()[0][0]);
Yes j'ai pas encore remplacé les calls

2021-12-04 00:09 UTC, 42njaber commented on inc/Object/GLObject.class.hpp
> +				processMesh(aiMesh* mesh, const aiScene* scene);
C'était pour le static, en effet, c'est pas dans le bon ordre '^^

2021-12-04 00:13 UTC, 42njaber commented on inc/Object/GLMesh.class.hpp
> +		void	draw(GLShaderProgram *shader) const;
Dans ce cas y'as même pas besoins d'envoyer le shader nan? Et du coup si on fait GLObject en hiérarchie récursive faudra envoyer la matrice au draw de GLObject par contre

2021-12-06 17:02 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		unsigned int const	getPolygonMode() const;
En vrai pour un int/uint je suis pas sur du plus opti entre aller chercher l'addresse et re allouer 4 octets lol

2021-12-06 17:18 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			GLObject(std::string path);
Pour le coup je sais pas, ça donnerait un GLObject avec des Mesh (qui contiennent des GLMesh)? Ça fonctionne pas vraiment

2021-12-06 17:20 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			std::vector<std::shared_ptr<GLMesh>>		meshes;
Les objets contiennent maintenant des Mesh (et non des GLMesh) et ceux si vont êtres modifiées (transfo + matrice). Le getter renvoie tout de meme un const.

2021-12-06 17:23 UTC, lnicosia commented on inc/Object/GLObject.class.hpp
> +			std::string	directory;
On en a besoin pour load les material qui sont placés dans le même dossier que l'objet

2021-12-08 11:25 UTC, lnicosia commented on inc/Object/GLMesh.class.hpp
> +		void	draw(GLShaderProgram *shader) const;
Au final ca prend bien la matrice 👍

2021-12-13 08:29 UTC, merged